server:
  port: 8080
  servlet:
    context-path: /record




spring:
  redis:
    host: localhost
    port: 6379
    password: null
    jedis:
      pool:
        max-active: 100
        max-wait: 1000
        max-idle: 10
        min-idle: 10
#  数据源组件
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://223.112.24.204:3306/record?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.htsc

test:
  height: 1.65
  content: "height: ${height}"